on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write # Required for OIDC trusted publishing
  contents: write # Needed to create releases
  pull-requests: write # Needed to create PRs

name: release-please
jobs:
  test-solidity:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-test.yml@main
    secrets:
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
    with:
      compareLcov: false
      compareGas: false

  test-node:
    uses: bgd-labs/github-workflows/.github/workflows/test-node.yml@main
    secrets: inherit

  release-please:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - test-solidity
      - test-node
    outputs:
      releaseCreated: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.AUTOMATION_APP_ID }}
          private-key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # pin@v4.4.0
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: node

      - uses: actions/checkout@v6
        if: ${{ !steps.release.outputs.release_created}}

      - name: Approve pr
        if: ${{ !steps.release.outputs.release_created }}
        run: |
          PR_NUMBER=$(echo '${{ steps.release.outputs.pr }}' | jq -r '.number')
          gh pr review --approve "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

      - name: Enable Pull Request Automerge
        if: ${{ !steps.release.outputs.release_created }}
        run: |
          PR_NUMBER=$(echo '${{ steps.release.outputs.pr }}' | jq -r '.number')
          gh pr merge --squash --auto "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          GH_REPO: ${{ github.repository }}

  release-node:
    if: ${{ needs.release-please.outputs.releaseCreated }}
    uses: bgd-labs/github-workflows/.github/workflows/release-node.yml@main
    needs: release-please

  release-node-alpha:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    needs:
      - test-solidity-pr
      - test-node-pr
    uses: bgd-labs/github-workflows/.github/workflows/release-node-alpha.yml@main
