name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  pkg-size-report:
    permissions:
      pull-requests: write
    name: Package Size Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v3

      - uses: bgd-labs/github-workflows/.github/actions/setup-node@main

      - name: Package size report
        uses: bgd-labs/size-limit-action@ae1e75a19db162bbc72bc446f60c4dfd2f27583f # pin@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          min_delta: 2
