name: Test & alpha release

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  test-solidity:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-test.yml@main
    secrets:
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
    with:
      compareLcov: false
      compareGas: false

  test-js:
    uses: bgd-labs/github-workflows/.github/workflows/test-node.yml@main
    if: github.event.pull_request.head.repo.full_name == github.repository
    secrets: inherit
  pkg-size-report:
    permissions:
      pull-requests: write
    name: Package Size Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # pin@v3

      - uses: bgd-labs/github-workflows/.github/actions/setup-node@main

      - name: Package size report
        uses: bgd-labs/size-limit-action@ae1e75a19db162bbc72bc446f60c4dfd2f27583f # pin@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          min_delta: 2

  release-node-alpha:
    if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    uses: bgd-labs/github-workflows/.github/workflows/release-node-alpha.yml@main
    needs:
      - test-solidity
      - test-js
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
