name: Test & alpha release

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  test-solidity:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-test.yml@main
    secrets:
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
    with:
      compareLcov: false
      compareGas: false

  test-js:
    uses: bgd-labs/github-workflows/.github/workflows/test-node.yml@main
    if: github.event.pull_request.head.repo.full_name == github.repository
    secrets: inherit
  pkg-size-report:
    permissions:
      pull-requests: write
    name: Package Size Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v3

      - uses: bgd-labs/github-workflows/.github/actions/setup-node@main

      - name: Package size report
        uses: andresz1/size-limit-action@94bc357df29c36c8f8d50ea497c3e225c3c95d1d # pin@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  release-node-alpha:
    if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    uses: bgd-labs/github-workflows/.github/workflows/release-node-alpha.yml@main
    needs:
      - test-solidity
      - test-js
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
